import { useState } from 'react';
import { useNavigate } from 'react-router';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { AlertBanner } from '../components/qms/AlertBanner';
import { Badge } from '../components/ui/badge';
import { Textarea } from '../components/ui/textarea';
import { ChevronDown, ChevronUp, Sparkles, Info, Edit2, Check, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../components/ui/dialog';
import { Label } from '../components/ui/label';
import { StatusBadge } from '../components/qms/StatusBadge';
import { AIResponse, impactLevelToStatus } from '../types/aiResponse';
import { ImpactCard } from '../components/qms/ImpactCard';
import { exampleGxpDeviationWithChangeControl } from '../lib/mockAIResponses';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '../components/ui/tooltip';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';

export function AIRecommendation() {
  const navigate = useNavigate();
  const [expanded, setExpanded] = useState(false);
  const [showOverrideDialog, setShowOverrideDialog] = useState(false);
  const [overrideJustification, setOverrideJustification] = useState('');
  // In production, this would come from an API call
  const [aiResponse, setAiResponse] = useState<AIResponse>(exampleGxpDeviationWithChangeControl);
  const [isEditingSeverity, setIsEditingSeverity] = useState(false);
  const [editedSeverity, setEditedSeverity] = useState(aiResponse.severity);
  const [originalSeverity] = useState(exampleGxpDeviationWithChangeControl.severity);
  const severityWasEdited = aiResponse.severity !== originalSeverity;

  const handleAccept = () => {
    navigate('/deviation/immediate-correction');
  };

  const handleOverride = () => {
    if (overrideJustification.trim()) {
      setShowOverrideDialog(false);
      navigate('/deviation/immediate-correction');
    }
  };

  const handleSaveSeverity = () => {
    setAiResponse({ ...aiResponse, severity: editedSeverity });
    setIsEditingSeverity(false);
  };

  const handleCancelSeverity = () => {
    setEditedSeverity(aiResponse.severity);
    setIsEditingSeverity(false);
  };

  const getSeverityBadgeClass = (severity: string): string => {
    const normalized = severity.toLowerCase();
    if (normalized === 'critical' || normalized === 'high') return 'bg-red-100 text-red-800 border-red-200';
    if (normalized === 'major' || normalized === 'medium') return 'bg-orange-100 text-orange-800 border-orange-200';
    if (normalized === 'minor' || normalized === 'low') return 'bg-green-100 text-green-800 border-green-200';
    return 'bg-gray-100 text-gray-600 border-gray-200';
  };

  const getClassificationDisplay = (classification: string): string => {
    if (classification === 'gxp_deviation') return 'GxP Deviation';
    if (classification === 'non_gxp_deviation') return 'Non-GxP Deviation';
    if (classification === 'planned_departure') return 'Planned Departure';
    return classification;
  };

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-900">AI Classification</h1>
        <p className="text-sm text-gray-500 mt-1">Review AI-generated classification and severity</p>
      </div>

      <div className="space-y-6">
        {/* Alert Banner */}
        <AlertBanner
          type="info"
          title="AI Suggestion – Requires Human Decision"
          message="The following classification has been generated by AI based on the deviation details. Please review and confirm or override as needed."
        />

        {/* AI Recommendation Card */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-blue-600" />
              AI Classification
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Classification */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-sm font-medium text-gray-600">Classification:</span>
                <Badge className={getSeverityBadgeClass(aiResponse.severity)}>
                  {getClassificationDisplay(aiResponse.classification)}
                </Badge>
              </div>
            </div>

            {/* Severity */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-sm font-medium text-gray-600">Severity Level:</span>
                {!isEditingSeverity ? (
                  <>
                    <StatusBadge status={aiResponse.severity as any} />
                    {severityWasEdited && (
                      <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200 text-xs">
                        Manually Edited
                      </Badge>
                    )}
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setIsEditingSeverity(true)}
                      className="h-7 px-2 text-xs"
                    >
                      <Edit2 className="h-3 w-3 mr-1" />
                      Edit
                    </Button>
                  </>
                ) : (
                  <div className="flex items-center gap-2">
                    <Select value={editedSeverity} onValueChange={setEditedSeverity}>
                      <SelectTrigger className="w-32 h-8">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="Critical">Critical</SelectItem>
                        <SelectItem value="Major">Major</SelectItem>
                        <SelectItem value="Minor">Minor</SelectItem>
                      </SelectContent>
                    </Select>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleSaveSeverity}
                      className="h-7 px-2 text-green-700 hover:text-green-800 hover:bg-green-50"
                    >
                      <Check className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleCancelSeverity}
                      className="h-7 px-2 text-gray-600 hover:text-gray-800 hover:bg-gray-50"
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  </div>
                )}
              </div>
            </div>

            {/* Confidence Score */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-1">
                  <span className="text-sm font-medium text-gray-600">AI Confidence Score</span>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <Info className="h-3.5 w-3.5 text-gray-400 cursor-help" />
                      </TooltipTrigger>
                      <TooltipContent className="max-w-xs">
                        <p className="text-xs">
                          Confidence is calculated based on predefined business rules and data completeness, not raw LLM confidence.
                        </p>
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
                <span className="text-sm font-semibold text-gray-900">{aiResponse.confidence_score}%</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div
                  className="bg-green-500 h-2 rounded-full"
                  style={{ width: `${aiResponse.confidence_score}%` }}
                ></div>
              </div>
            </div>

            {/* Expandable Rationale */}
            <div className="border-t pt-4">
              <button
                onClick={() => setExpanded(!expanded)}
                className="flex items-center justify-between w-full text-sm font-medium text-gray-900"
              >
                <span>AI Rationale</span>
                {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
              </button>

              {expanded && (
                <div className="mt-3 space-y-2 text-sm text-gray-600 whitespace-pre-line">
                  {aiResponse.rationale}
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Initial Impact Assessment */}
        <Card>
          <CardHeader>
            <CardTitle>Initial Impact Assessment</CardTitle>
            <p className="text-xs text-gray-500 mt-1">Preliminary impact screening - detailed assessment follows later in the workflow</p>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <ImpactCard
                category="Patient Safety"
                status={impactLevelToStatus(aiResponse.impact_assessment.patient_safety)}
                description={`Impact level: ${aiResponse.impact_assessment.patient_safety}`}
              />
              <ImpactCard
                category="Product Quality"
                status={impactLevelToStatus(aiResponse.impact_assessment.product_quality)}
                description={`Impact level: ${aiResponse.impact_assessment.product_quality}`}
              />
              <ImpactCard
                category="Data Integrity"
                status={impactLevelToStatus(aiResponse.impact_assessment.data_integrity)}
                description={`Impact level: ${aiResponse.impact_assessment.data_integrity}`}
              />
              <ImpactCard
                category="Regulatory Compliance"
                status={impactLevelToStatus(aiResponse.impact_assessment.regulatory)}
                description={`Impact level: ${aiResponse.impact_assessment.regulatory}`}
              />
              <ImpactCard
                category="Validated State"
                status={impactLevelToStatus(aiResponse.impact_assessment.validated_state)}
                description={`Impact level: ${aiResponse.impact_assessment.validated_state}`}
              />
            </div>
          </CardContent>
        </Card>

        {/* Recommended Actions */}
        <Card>
          <CardHeader>
            <CardTitle>Recommended Actions</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {aiResponse.recommended_actions.map((action, index) => (
                <li key={index} className="flex items-start gap-2 text-sm text-gray-700">
                  <span className="text-blue-600 font-semibold shrink-0">{index + 1}.</span>
                  <span>{action}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Action Buttons - only show if human confirmation is required */}
        {aiResponse.requires_human_confirmation && (
          <Card>
            <CardHeader>
              <CardTitle>Decision Required</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex gap-4">
                <Button
                  onClick={handleAccept}
                  className="flex-1 bg-green-600 hover:bg-green-700"
                >
                  Accept Classification
                </Button>
                <Button
                  onClick={() => setShowOverrideDialog(true)}
                  variant="outline"
                  className="flex-1"
                >
                  Override Classification
                </Button>
              </div>
              <p className="text-xs text-gray-500 mt-3 text-center">
                Your decision will be logged in the audit trail
              </p>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Override Dialog */}
      <Dialog open={showOverrideDialog} onOpenChange={setShowOverrideDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Override AI Classification</DialogTitle>
            <DialogDescription>
              Please provide a justification for overriding the AI recommendation. This will be recorded in the audit trail.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="justification">Justification *</Label>
              <Textarea
                id="justification"
                placeholder="Explain why you are overriding the AI classification..."
                rows={4}
                value={overrideJustification}
                onChange={(e) => setOverrideJustification(e.target.value)}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowOverrideDialog(false)}>
              Cancel
            </Button>
            <Button 
              onClick={handleOverride}
              disabled={!overrideJustification.trim()}
            >
              Confirm Override
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
